# Generated by Django 4.2.2 on 2023-06-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_producto_fecha_creacion_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='assets/img/default.jpg', upload_to='assets/img/'),
        ),
    ]
